-- begin ICVRETAIL_PRODUCTS
create unique index IDX_ICVRETAIL_PRODUCTS_UNIQ_NUMBER_ on ICVRETAIL_PRODUCTS (NUMBER_) ^
-- end ICVRETAIL_PRODUCTS
-- begin ICVRETAIL_INVOICES
alter table ICVRETAIL_INVOICES add constraint FK_ICVRETAIL_INVOICES_COUNTERPARTY foreign key (COUNTERPARTY_ID) references ICVRETAIL_COUNTERPARTIES(ID)^
alter table ICVRETAIL_INVOICES add constraint FK_ICVRETAIL_INVOICES_WAREHOUSE foreign key (WAREHOUSE_ID) references ICVRETAIL_WAREHOUSES(ID)^
create index IDX_ICVRETAIL_INVOICES_COUNTERPARTY on ICVRETAIL_INVOICES (COUNTERPARTY_ID)^
create index IDX_ICVRETAIL_INVOICES_WAREHOUSE on ICVRETAIL_INVOICES (WAREHOUSE_ID)^
-- end ICVRETAIL_INVOICES
-- begin ICVRETAIL_PURCHASES
alter table ICVRETAIL_PURCHASES add constraint FK_ICVRETAIL_PURCHASES_COUNTERPARTY foreign key (COUNTERPARTY_ID) references ICVRETAIL_COUNTERPARTIES(ID)^
alter table ICVRETAIL_PURCHASES add constraint FK_ICVRETAIL_PURCHASES_WAREHOUSE foreign key (WAREHOUSE_ID) references ICVRETAIL_WAREHOUSES(ID)^
create index IDX_ICVRETAIL_PURCHASES_COUNTERPARTY on ICVRETAIL_PURCHASES (COUNTERPARTY_ID)^
create index IDX_ICVRETAIL_PURCHASES_WAREHOUSE on ICVRETAIL_PURCHASES (WAREHOUSE_ID)^
-- end ICVRETAIL_PURCHASES
-- begin ICVRETAIL_INVOICE_PRODUCT_LINES
alter table ICVRETAIL_INVOICE_PRODUCT_LINES add constraint FK_ICVRETAIL_INVOICE_PRODUCT_LINES_INVOICES foreign key (INVOICES_ID) references ICVRETAIL_INVOICES(ID)^
alter table ICVRETAIL_INVOICE_PRODUCT_LINES add constraint FK_ICVRETAIL_INVOICE_PRODUCT_LINES_PRODUCT foreign key (PRODUCT_ID) references ICVRETAIL_PRODUCTS(ID)^
create index IDX_ICVRETAIL_INVOICE_PRODUCT_LINES_INVOICES on ICVRETAIL_INVOICE_PRODUCT_LINES (INVOICES_ID)^
create index IDX_ICVRETAIL_INVOICE_PRODUCT_LINES_PRODUCT on ICVRETAIL_INVOICE_PRODUCT_LINES (PRODUCT_ID)^
-- end ICVRETAIL_INVOICE_PRODUCT_LINES
-- begin ICVRETAIL_PURCHASE_PRODUCT_LINES
alter table ICVRETAIL_PURCHASE_PRODUCT_LINES add constraint FK_ICVRETAIL_PURCHASE_PRODUCT_LINES_PRODUCT foreign key (PRODUCT_ID) references ICVRETAIL_PRODUCTS(ID)^
alter table ICVRETAIL_PURCHASE_PRODUCT_LINES add constraint FK_ICVRETAIL_PURCHASE_PRODUCT_LINES_PURCHASES foreign key (PURCHASES_ID) references ICVRETAIL_PURCHASES(ID)^
create index IDX_ICVRETAIL_PURCHASE_PRODUCT_LINES_PRODUCT on ICVRETAIL_PURCHASE_PRODUCT_LINES (PRODUCT_ID)^
create index IDX_ICVRETAIL_PURCHASE_PRODUCT_LINES_PURCHASES on ICVRETAIL_PURCHASE_PRODUCT_LINES (PURCHASES_ID)^
-- end ICVRETAIL_PURCHASE_PRODUCT_LINES
-- begin ICVRETAIL_WAREHOUSE_BALANCE
alter table ICVRETAIL_WAREHOUSE_BALANCE add constraint FK_ICVRETAIL_WAREHOUSE_BALANCE_WAREHOUSE foreign key (WAREHOUSE_ID) references ICVRETAIL_WAREHOUSES(ID)^
alter table ICVRETAIL_WAREHOUSE_BALANCE add constraint FK_ICVRETAIL_WAREHOUSE_BALANCE_PRODUCT foreign key (PRODUCT_ID) references ICVRETAIL_PRODUCTS(ID)^
create index IDX_ICVRETAIL_WAREHOUSE_BALANCE_WAREHOUSE on ICVRETAIL_WAREHOUSE_BALANCE (WAREHOUSE_ID)^
create index IDX_ICVRETAIL_WAREHOUSE_BALANCE_PRODUCT on ICVRETAIL_WAREHOUSE_BALANCE (PRODUCT_ID)^
-- end ICVRETAIL_WAREHOUSE_BALANCE
